services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=tasksapp
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=f2020065221
      - NODE_ENV=development
    ports:
      - "1337:1337"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: tasksapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "f2020065221"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
