services:
  strapi:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '1337:1337'
    volumes:
      - ./server:/usr/src/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: tasksapp
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: f2020065221

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: tasksapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: f2020065221
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
